### ISSUE TITLE
Revive monsters that died due to technical issues

### ISSUE THREAD

**Issue by friedger** [MonsterEOS/monstereos#60]
Last night (26/27 July 2018) there seemed to be a problem with scatter, the network or so.

Should the monsters that couldn't be fed be revived?

In particular user gu2tsnzsgige and ha4toobwguge complained about technical issues.

**Comment by friedger** [comment]
![gu2tsnzsgige](https://user-images.githubusercontent.com/1449049/43328011-3efdaf8a-91bd-11e8-87bd-7ca25b0a4eaf.png)
![ha4toobwguge](https://user-images.githubusercontent.com/1449049/43328012-3f21efee-91bd-11e8-9f2e-98f24622b4fe.png)

**Comment by solartones** [comment]
ha4toobwguge
my deathlist...
Cheers!!

2262
2287
2294
2299
2349
2354
2368
2834
3067

**Comment by Conner72** [comment]
Here you go 
and thanks in Advance for Helping No matter the outcome.....

I would also like to make it clear that I am not endorsing or agreeing with the idea that monster be brought back to life. This option should ONLY be used For Technical issues that can be proven not to have been neglect. Part of the fun of this game is the Finality of Death.  Like Dan Said Code is Not Law The Intention of the Code is Law......


![my monsters](https://user-images.githubusercontent.com/41799225/43332445-8203cfde-9196-11e8-953f-c75c509d31d6.PNG)

**Comment by ryad-eldajani** [comment]
Today it seemed to happen again.
I'm 100% sure, I've feeded my pets this morning, all bars were filled. But now they're all gone... I've looked up the blockchain and it looks like the transactions were kind of removed. This is really frustrating.

However, since there are a lot of pets removed from the first page, which rarely happened recently, I guess I'm not the only one.

**Comment by leordev** [comment]
@ryad-eldajani that's strange because we didn't have any feedback on monsters channel...

**Comment by leordev** [comment]
@friedger not as simple as I imagined. we will need to create a revive action that requires the contract auth to do that, I will do this with the market deploy.

**Comment by leordev** [comment]
@ryad-eldajani @solartones @Conner72 we are going to deploy the new changes in the next couple days, please be aware because your monsters will be revived (if you didn't delete them)

**Comment by leordev** [comment]
@ryad-eldajani I need your monsters ids.

**Comment by Conner72** [comment]
Ok great I only have one monster left Chaos Monkey the other was deleted

On Sep 14, 2018 6:41 AM, "Leo Ribeiro" <notifications@github.com> wrote:

@ryad-eldajani <https://github.com/ryad-eldajani> @solartones
<https://github.com/solartones> @Conner72 <https://github.com/Conner72> we
are going to deploy the new changes in the next couple days, please be
aware because your monsters will be revived (if you didn't delete them)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/MonsterEOS/monstereos/issues/60#issuecomment-421316681>,
or mute the thread

**Comment by friedger** [comment]
Monsters have been revived!

**Comment by ryad-eldajani** [comment]
@friedger That's really cool. Unfortunately I cannot confirm that in my case. I guess @leordev is going to do that in near future since he has my IDs. However, it's great news, thank you guys!

**Comment by leordev** [comment]
@ryad-eldajani please check them again!

**Comment by ryad-eldajani** [comment]
@leordev Very nice! Thank you so much :+1:
