### ISSUE TITLE
Write down and open to public our Distribution and DAO Scheme

### ISSUE THREAD

**Issue by leordev** [MonsterEOS/monstereos#72]

**Comment by Velua** [comment]
*Rough draft so far...*

# MonsterEOS Contribution Framework
## Background
Following our partnership with Vertex, we deem it necessary to use another framework for distribution of rewards as well as making big decisions amongst our team.

## Shares
Like in the previous system, actors are imbursed based on the amount of time they've spent. One of the flaws of this is that the system failed to reimburse anyone outside of the 2 week dividend periods which can lead to people missing out unfairly.

Going forward, shares are distributed to contributors based on their amount of decimal hours times their weight times by 2.

E.g.
(3.5 hours * 1) * 2 = 7 shares.

These shares are kept perpetually for as long as this system is in use. 
This way, a contributor can have 200 shares and receive a dividend ongoing.  

Should a contributor no longer contribute and therefore stop receiving further shares, they're weight in dividends will slowly erode due to inflation created by ongoing contributors.

# Dividends
Dividends are every two weeks, a dividend amount is subject to be changed by the board. Without intervention, an amount to share is decided by the board, 20% of it is created as a Board dividend and the remaining 80% a share dividend.

Sharing amount: 26 EOS
Board Dividend: 5.2 EOS
Share Dividend: 20.8 EOS

## Board dividend distribution based on data below. 
(6/21 * 5.2) Leo: 1.48 EOS
(6/21 * 5.2) John: 1.48 EOS
(6/21 * 5.2) Vertex: 1.48 EOS
(3/21 * 5.2) Friedger: 0.74 EOS

## Share Distribution in a period
(6 * 2) Leo: 12 Shares Awarded
(2 * 2) John: 4 Shares Awarded
(8 * 2) Vertex:  16 Shares Awarded
(2 * 2)Friedger): 4 Shares Awarded
Total hours: 18
Shares Awarded: 36
Total Shares Existing: 254 (random number)

Claim
0.0818 EOS per share
(77 Shares) Leo: 6.30 EOS 
(50 Shares) John: 4.09 EOS
(107 Shares) Vertex: 8.76 EOS
(20 Shares) Friedger: 1.63 EOS

**Comment by leordev** [comment]
https://github.com/MonsterEOS/dao/blob/master/README.md
